language: c
sudo: false

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.stack

matrix:
  include:
    - env: BUILD=stack GHCVER=7.10.3 STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3"
      addons: {apt: {packages: [ghc-7.10.3], sources: [hvr-ghc]}}

    - env: BUILD=stack STACK_YAML=stack.yaml
      compiler: ": #stack 7.10.3 osx"
      os: osx

# Note: the distinction between `before_install` and `install` is not important.
# - in before_install we install build tools
# - in install we install (haskell) dependencies
before_install:
 - unset CC
 - export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;;
 - ./.travis-setup.sh

install:
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - stack --no-terminal test --only-dependencies;;

script:
 - stack --no-terminal build;;
